### PR TITLE
allow to set dot.templateSettings

### PR DESCRIPTION
**Pull request by tomyam1**
allow to set dot.templateSettings. This allows to do something like:

```
        dot: {
            dist: {
                options: {
                   ...
                    templateSettings : {
                        evaluate:    /\{\%([\s\S]+?)\%\}/g,
                        interpolate: /\{\%=([\s\S]+?)\%\}/g,
                        encode:      /\{\%!([\s\S]+?)\%\}/g,
                        use:         /\{\%#([\s\S]+?)\%\}/g,
                        define:      /\{\%##\s*([\w\.$]+)\s*(\:|=)([\s\S]+?)#\%\}/g,
                        conditional: /\{\%\?(\?)?\s*([\s\S]*?)\s*\%\}/g,
                        iterate:     /\{\%~\s*(?:\}\}|([\s\S]+?)\s*\:\s*([\w$]+)\s*(?:\:\s*([\w$]+))?\s*\%\})/g,
                        varname: 'it',
                        strip: true,
                        append: true,
                        selfcontained: false
                    }
                },
             ...
            }
        },
```

add missing semicolon

### CODE REVIEW

**Comment by tomyam1** [comment]
Well, this PR is not ready to merge yet. This task uses some regex for partial detection, loading of partial templates, etc. These regex are hard-coded and does not derive from `doT.templateSettings`. 

As a results, if you change the the regex in `doT.templateSettings`, the template will compile, but `grunt-dot-compiler`'s partial detection will not work.

I just started using `grunt` and does not feel up to the task. Is this a feature you'd be interested in adding to this task?

**Comment by tinganho** [comment]
Right now, I wouldn't add this feature.

**Comment by salzhrani** [comment]
Why not ?

**Comment by tinganho** [comment]
@salzhrani I intend to create a new template engine from a fork of doT. There is a lot that we can do to make doT even faster. But the author of doT isn't active. I have halted any further feature development of `grunt-dot-compiler`. Just bugs will be fixed.

**Pull request closed without merging**
