### PR TITLE
Correctly strip JS comments

### PR DESCRIPTION
**Pull request by sdemjanenko**
I noticed that http(s):// were getting removed.

### CODE REVIEW

**Comment by sdemjanenko** [comment]
Actually this doesn't seem to quite work.  I will add tests and see if I can make them pass.  The comment stripper also fails when the last line has a comment.

**Comment by tinganho** [comment]
@sdemjanenko Do you have any PR on this?

**Comment by sdemjanenko** [comment]
I just submitted a pull request for a fix.

**Comment by tinganho** [comment]
Your changes is now published to to NPM v.0.5.4

**Pull request closed without merging**
