### PR TITLE
Updated documentation, semicolon fixes, and simple mode that doesn't produce module.exports

### PR DESCRIPTION
**Pull request by Leonas**
My commit messages have detailed comments about the fixes

### CODE REVIEW

**Comment by tinganho** [comment]
Thanks for your PR. I will take a look at it later next week

**Comment by tinganho** [comment]
I will add an another solution for simple compiling. I think the cleanest solution is to omit requirejs and node.

**Comment by tinganho** [comment]
@Leonas Just make sure you have v-0.3.12 of grunt-dot-compiler. If you omit both requirejs and node it will compile the solution you asked for

**Comment by Leonas** [comment]
When I set node and requirejs to false, it wasn't compiling and if I set node to true it would also add some extra stuff at the bottom which I didn't need. Anyway, thanks for making this compiler! :smile:

**Pull request closed without merging**
