### PR TITLE
Allow namespaced variable

### PR DESCRIPTION
**Pull request by fadomire**
variable : "myNamespace.util.template" will now work and define object and sub object properly

### CODE REVIEW

**Comment by tinganho** [comment]
I will merge in your code and publish it later thanks for your support

**Comment by fadomire** [comment]
No problem, i needed that feature, so just thought i would share it back. 

Thanks for your plugin, it is usefull.

**Comment by fadomire** [comment]
Could you reopen this pull request i just modified test case for the build to pass ?

**Comment by tinganho** [comment]
@fadomire I can't re-open when I merged your things on Github. Can you make a new PR?

**Comment by fadomire** [comment]
@tinganho ok done.

**Comment by tinganho** [comment]
thanks

**Pull request merged**
